### ISSUE TITLE
Missing store.h

### ISSUE THREAD

**Issue by peterstanton** [Kakarot87/moviestore#1]
There is no header file for the Store class.

**Comment by Kakarot87** [comment]
Show me what you were thinking  and I'll weigh in. I'm working on the diagram

**Comment by peterstanton** [comment]
Something like this would work for Store, I think.

`#ifndef STORE_H
#define STORE_H
#include iostream
#include "hashtable.h"
#include "binarysearchtree.h"

using namespace std;

class Store {
	
public:

	Store();
	Store(const Store*);
	~Store();
	void runStore();
	void readCustomers();
	void readMovies();
	void readCommands()
	
private: 
	BinarySearchTree inventoryDatabase;
	HashTable customerDatabase;
};

#endif`

**Comment by Kakarot87** [comment]
A few typos but I'm committing now

**Comment by peterstanton** [comment]
Cool, do you know what else we need to do with the word doc?

**Comment by peterstanton** [comment]
It also just occurred to me that we need a Queue.h and Store.h should contain a Queue of transactions.
